version: '3'
services: 
  rabbitmq3: 
    image: rabbitmq:3-management
    environment: 
     - RABBITMQ_ERLANG_COOKIE='secret cookie here'
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
    volumes: 
      - ./storage:/var/lib/rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
