server:
  port: 8761
  servlet:
    context-path: /registry

spring:
  application:
    name: eureka-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localho:${server.port}/eureka


logging:
  file:
    name: ../log/ms_discovery_log/appfile.log